// ts-rosetta/apps/solid/src/Board.tsx
// Solid board: JSX like React, but there is NO re-render. Components run
// ONCE; each {expression} compiles to a fine-grained effect that patches
// its own DOM node. A store path update touches exactly the cells that
// read the changed fields — the "optimized React" architecture is simply
// how Solid works by default.
import { For, Show, batch, createSignal, onCleanup } from 'solid-js';
import { createStore } from 'solid-js/store';
import {
  TickEngine,
  PerfMeter,
  type Quote,
  type PerfSample,
} from '@rosetta/core';

const SYMBOL_CHOICES = [50, 200, 1000, 5000];
const RATE_CHOICES = [10, 40, 60];
const FRACTION = 0.1;

export default function Board() {
  const [symbols, setSymbols] = createSignal(200);
  const [rate, setRate] = createSignal(40);
  const [running, setRunning] = createSignal(false);
  const [sample, setSample] = createSignal<PerfSample | null>(null);
  const [rows, setRows] = createStore<Quote[]>([]);
  const perf = new PerfMeter();
  perf.onSample = setSample;
  let engine: TickEngine | null = null;

  function stop() {
    engine?.stop();
    engine = null;
    perf.stop();
    setRunning(false);
  }

  function start() {
    stop();
    const e = new TickEngine({
      symbols: symbols(),
      rate: rate(),
      fraction: FRACTION,
      onTick: (updates) => {
        perf.countUpdates(updates.length);
        batch(() => {
          for (const u of updates) {
            // Path update: merges into the row proxy → cell-level effects.
            setRows(u.index, {
              last: u.last,
              bid: u.bid,
              ask: u.ask,
              changePct: u.changePct,
              dir: u.dir,
            });
          }
        });
      },
    });
    setRows(e.book.map((q) => ({ ...q })));
    engine = e;
    e.start();
    perf.start();
    setRunning(true);
  }

  function toggle() {
    if (running()) stop();
    else start();
  }

  function pickSymbols(n: number) {
    setSymbols(n);
    if (running()) start();
  }

  function pickRate(r: number) {
    setRate(r);
    if (running()) start();
  }

  onCleanup(stop);

  return (
    <main class="app board">
      <h1>
        Live Board <span class="badge">Solid 1.9</span>
        <a class="badge" href="http://localhost:8080">dashboard</a>
      </h1>

      <section class="row board-controls">
        <span class="stats">work = last-cell effect runs</span>
      </section>

      <section class="row board-controls">
        <For each={SYMBOL_CHOICES}>
          {(n) => (
            <button
              data-symbols={n}
              classList={{ on: symbols() === n }}
              onClick={() => pickSymbols(n)}
            >
              {n}
            </button>
          )}
        </For>
        <span>symbols</span>
        <For each={RATE_CHOICES}>
          {(r) => (
            <button data-rate={r} classList={{ on: rate() === r }} onClick={() => pickRate(r)}>
              {r}/s
            </button>
          )}
        </For>
        <button data-action="toggle" onClick={toggle}>
          {running() ? 'Stop' : 'Start'}
        </button>
      </section>

      <p class="board-stats">
        <span>
          <span data-stat="fps">{sample()?.fps ?? '–'}</span> fps
        </span>
        <span>
          <span data-stat="long">{sample()?.longTotal ?? 0}</span> long
        </span>
        <span>
          <span data-stat="upd">{sample()?.updatesPerSec ?? 0}</span> upd/s
        </span>
        <span>
          <span data-stat="work">{sample()?.workPerSec ?? 0}</span> work/s
        </span>
      </p>

      <Show
        when={running()}
        fallback={
          <p class="board-idle">
            Press Start — {symbols()} symbols, {rate()} ticks/s
          </p>
        }
      >
        <div class="board-wrap">
          <table class="board-grid">
            <thead>
              <tr>
                <th>Symbol</th>
                <th>Last</th>
                <th>Bid</th>
                <th>Ask</th>
                <th>Chg%</th>
              </tr>
            </thead>
            <tbody>
              <For each={rows}>
                {(q) => (
                  <tr>
                    <td class="sym">{q.symbol}</td>
                    <td class={q.dir === 1 ? 'up' : q.dir === -1 ? 'down' : ''}>
                      {q.dir === 1 ? '▲ ' : q.dir === -1 ? '▼ ' : ''}
                      {/* comma expression: counting rides on the effect that
                          re-runs whenever this row's `last` changes */}
                      {(perf.countWork(1), q.last.toFixed(2))}
                    </td>
                    <td>{q.bid.toFixed(2)}</td>
                    <td>{q.ask.toFixed(2)}</td>
                    <td class={q.changePct >= 0 ? 'up' : 'down'}>
                      {q.changePct >= 0 ? '+' : ''}
                      {q.changePct.toFixed(2)}%
                    </td>
                  </tr>
                )}
              </For>
            </tbody>
          </table>
        </div>
      </Show>
    </main>
  );
}

// ts-rosetta/apps/react/src/Board.tsx
import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import {
  TickEngine,
  PerfMeter,
  type Quote,
  type PerfSample,
} from '@rosetta/core';
import { BoardStore, FRACTION } from './boardStore';

type BoardMode = 'naive' | 'optimized';
const SYMBOL_CHOICES = [50, 200, 1000, 5000];
const RATE_CHOICES = [10, 40, 60];

/* ---------- shared row view (dumb, identical in both modes) ---------- */

function RowView({ q }: { q: Quote }) {
  return (
    <tr>
      <td className="sym">{q.symbol}</td>
      <td className={q.dir === 1 ? 'up' : q.dir === -1 ? 'down' : ''}>
        {q.dir === 1 ? '▲ ' : q.dir === -1 ? '▼ ' : ''}
        {q.last.toFixed(2)}
      </td>
      <td>{q.bid.toFixed(2)}</td>
      <td>{q.ask.toFixed(2)}</td>
      <td className={q.changePct >= 0 ? 'up' : 'down'}>
        {q.changePct >= 0 ? '+' : ''}
        {q.changePct.toFixed(2)}%
      </td>
    </tr>
  );
}

function GridHead() {
  return (
    <thead>
      <tr>
        <th>Symbol</th>
        <th>Last</th>
        <th>Bid</th>
        <th>Ask</th>
        <th>Chg%</th>
      </tr>
    </thead>
  );
}

/* ---------- naive: one useState array, parent re-renders per tick ---------- */

function NaiveRow({ q, perf }: { q: Quote; perf: PerfMeter }) {
  // Runs for EVERY row on EVERY tick — the parent's setState re-renders
  // the whole list. This is the trap being measured.
  perf.countWork(1);
  return <RowView q={q} />;
}

function NaiveBoard({ symbols, rate, perf }: BoardProps) {
  const [quotes, setQuotes] = useState<Quote[]>([]);
  useEffect(() => {
    const engine = new TickEngine({
      symbols,
      rate,
      fraction: FRACTION,
      onTick: (updates) => {
        perf.countUpdates(updates.length);
        setQuotes((prev) => {
          const next = prev.slice();
          for (const u of updates) {
            next[u.index] = {
              ...next[u.index],
              last: u.last,
              bid: u.bid,
              ask: u.ask,
              changePct: u.changePct,
              dir: u.dir,
            };
          }
          return next;
        });
      },
    });
    setQuotes(engine.book.map((q) => ({ ...q })));
    engine.start();
    return () => engine.stop();
  }, [symbols, rate, perf]);

  return (
    <div className="board-wrap">
      <table className="board-grid">
        <GridHead />
        <tbody>
          {quotes.map((q) => (
            <NaiveRow key={q.symbol} q={q} perf={perf} />
          ))}
        </tbody>
      </table>
    </div>
  );
}

/* ---------- optimized: external store + per-row subscription ---------- */

function OptRow({ store, i, perf }: { store: BoardStore; i: number; perf: PerfMeter }) {
  // Re-renders ONLY when this row's slot in the store changes.
  const q = useSyncExternalStore(store.subscribes[i], store.snapshots[i]);
  perf.countWork(1);
  return <RowView q={q} />;
}

function OptBoard({ symbols, rate, perf }: BoardProps) {
  const [store] = useState(() => new BoardStore(symbols, rate, perf));
  useEffect(() => {
    store.engine.start();
    return () => store.engine.stop();
  }, [store]);

  return (
    <div className="board-wrap">
      <table className="board-grid">
        <GridHead />
        <tbody>
          {store.quotes.map((_, i) => (
            <OptRow key={store.quotes[i].symbol} store={store} i={i} perf={perf} />
          ))}
        </tbody>
      </table>
    </div>
  );
}

/* ---------- stats bar: isolates the 1/sec sample re-render ---------- */

function StatsBar({ perf }: { perf: PerfMeter }) {
  const [s, setS] = useState<PerfSample | null>(null);
  useEffect(() => {
    perf.onSample = setS;
    return () => {
      perf.onSample = undefined;
    };
  }, [perf]);
  return (
    <p className="board-stats">
      <span>
        <span data-stat="fps">{s?.fps ?? '–'}</span> fps
      </span>
      <span>
        <span data-stat="long">{s?.longTotal ?? 0}</span> long
      </span>
      <span>
        <span data-stat="upd">{s?.updatesPerSec ?? 0}</span> upd/s
      </span>
      <span>
        <span data-stat="work">{s?.workPerSec ?? 0}</span> work/s
      </span>
    </p>
  );
}

/* ---------- board shell ---------- */

interface BoardProps {
  symbols: number;
  rate: number;
  perf: PerfMeter;
}

export default function Board() {
  const [mode, setMode] = useState<BoardMode>('naive');
  const [symbols, setSymbols] = useState(200);
  const [rate, setRate] = useState(40);
  const [running, setRunning] = useState(false);
  const perfRef = useRef<PerfMeter | null>(null);
  perfRef.current ??= new PerfMeter();
  const perf = perfRef.current;

  useEffect(() => {
    if (!running) return;
    perf.start();
    return () => perf.stop();
    // restart the meter whenever the run config changes
  }, [running, mode, symbols, rate, perf]);

  const cfgKey = `${mode}-${symbols}-${rate}`;

  return (
    <main className="app board">
      <h1>
        Live Board <span className="badge">React 19 — {mode}</span>
        <a className="badge" href="#">
          ← tasks
        </a>
      </h1>

      <section className="row board-controls">
        {(['naive', 'optimized'] as const).map((m) => (
          <button
            key={m}
            data-mode={m}
            className={mode === m ? 'on' : ''}
            onClick={() => setMode(m)}
          >
            {m}
          </button>
        ))}
        <span className="stats">work = row renders</span>
      </section>

      <section className="row board-controls">
        {SYMBOL_CHOICES.map((n) => (
          <button
            key={n}
            data-symbols={n}
            className={symbols === n ? 'on' : ''}
            onClick={() => setSymbols(n)}
          >
            {n}
          </button>
        ))}
        <span>symbols</span>
        {RATE_CHOICES.map((r) => (
          <button
            key={r}
            data-rate={r}
            className={rate === r ? 'on' : ''}
            onClick={() => setRate(r)}
          >
            {r}/s
          </button>
        ))}
        <button data-action="toggle" onClick={() => setRunning(!running)}>
          {running ? 'Stop' : 'Start'}
        </button>
      </section>

      <StatsBar perf={perf} />

      {running ? (
        mode === 'naive' ? (
          <NaiveBoard key={cfgKey} symbols={symbols} rate={rate} perf={perf} />
        ) : (
          <OptBoard key={cfgKey} symbols={symbols} rate={rate} perf={perf} />
        )
      ) : (
        <p className="board-idle">Press Start — {symbols} symbols, {rate} ticks/s</p>
      )}
    </main>
  );
}
